name: ESLint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: yarn run lint